In [1]:
'''
NumPy, short for Numerical Python, is a fundamental package for scientific computing in Python.
It provides support for large, multi-dimensional arrays and matrices, along with a collection of 
mathematical functions to operate on these arrays efficiently. Numpy arrays are of two types
vectors 1-D arrays, matrices 2-D arrays
'''

'\nNumPy, short for Numerical Python, is a fundamental package for scientific computing in Python.\nIt provides support for large, multi-dimensional arrays and matrices, along with a collection of \nmathematical functions to operate on these arrays efficiently. Numpy arrays are of two types\nvectors 1-D arrays, matrices 2-D arrays\n'

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] 

In [8]:
np.array(my_mat) #

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [38]:
np.random.rand(5,5)

array([[0.28414548, 0.70683961, 0.1802957 , 0.42591006, 0.30193574],
       [0.57074935, 0.03824701, 0.3791329 , 0.23309151, 0.67639702],
       [0.7058801 , 0.55965189, 0.02127006, 0.54183969, 0.71692419],
       [0.52603518, 0.298263  , 0.69885748, 0.69285215, 0.54031739],
       [0.62387258, 0.54186021, 0.46822357, 0.88475058, 0.74658723]])

In [39]:
np.random.randint(1,100,100)

array([76, 12, 90, 67, 75, 47, 51, 26, 83, 56, 45, 28, 50, 16, 48, 19, 56,
       49, 90, 17, 96, 45, 46, 49, 18, 61, 68, 70, 90, 22, 17, 34, 29,  8,
       86, 15, 66, 43,  2, 24, 10, 62, 28, 45, 62, 82, 43, 86, 80, 18, 75,
       18, 53, 24, 14, 13, 89, 74, 15, 61, 53, 28, 71, 27, 66, 27, 85, 20,
       45, 46, 72,  4, 33, 28, 88, 90, 28, 57, 83, 77, 12, 43, 83, 45, 18,
       15, 81, 21, 34, 26, 96, 22, 11, 79, 12, 58, 16, 67, 45, 34])

In [46]:
arr= np.arange(50).reshape(5,10)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [13]:
#NumPy is widely used for numerical computing tasks such as arithmetic operations, linear algebra, and statistical analysis.

In [14]:
import numpy as np

# Arithmetic operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [15]:
# Linear algebra operations
matrix = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)

[-0.37228132  5.37228132]


In [16]:
# Statistical analysis
data = np.random.normal(loc=0, scale=1, size=1000)
mean = np.mean(data)
std_dev = np.std(data)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: -0.0325044713974724
Standard Deviation: 1.0053844089726238


In [17]:
data = np.random.normal(loc=0, scale=1, size=1000)

In [18]:
#NumPy provides efficient data structures and functions for manipulating large datasets.

In [19]:
import numpy as np

# Creating NumPy arrays
data = [1, 2, 3, 4, 5]
arr = np.array(data)

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
# Reshaping arrays
reshaped_arr = arr.reshape(1, 5)
print(reshaped_arr)

[[1 2 3 4 5]]


In [22]:
# Indexing and slicing
print(arr[2])  
print(arr[1:4])

3
[2 3 4]


In [23]:
#NumPy is a fundamental building block for implementing machine learning algorithms and handling data in machine learning tasks.

In [28]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [29]:
# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

In [30]:
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)



In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [32]:
# Initialize and train logistic regression model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [34]:
# Make predictions
y_pred = model.predict(X_test_scaled)



In [35]:
# Evaluate model performance
accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9666666666666667
