In [4]:
'''
NumPy, short for Numerical Python, is a fundamental package for scientific computing in Python.
It provides support for large, multi-dimensional arrays and matrices, along with a collection of 
mathematical functions to operate on these arrays efficiently. Numpy arrays are of two types
vectors 1-D arrays, matrices 2-D arrays
'''

'\nNumPy, short for Numerical Python, is a fundamental package for scientific computing in Python.\nIt provides support for large, multi-dimensional arrays and matrices, along with a collection of \nmathematical functions to operate on these arrays efficiently. Numpy arrays are of two types\nvectors 1-D arrays, matrices 2-D arrays\n'

In [5]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
my_list = [1,2,3]

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] 

In [12]:
np.array(my_mat) #

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
#NumPy is widely used for numerical computing tasks such as arithmetic operations, linear algebra, and statistical analysis.

In [19]:
import numpy as np

# Arithmetic operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [20]:
# Linear algebra operations
matrix = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)

[-0.37228132  5.37228132]


In [21]:
# Statistical analysis
data = np.random.normal(loc=0, scale=1, size=1000)
mean = np.mean(data)
std_dev = np.std(data)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: -0.0003652202716754154
Standard Deviation: 1.0121868959414189


In [22]:
data = np.random.normal(loc=0, scale=1, size=1000)

In [ ]:
#NumPy provides efficient data structures and functions for manipulating large datasets.

In [24]:
import numpy as np

# Creating NumPy arrays
data = [1, 2, 3, 4, 5]
arr = np.array(data)

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
# Reshaping arrays
reshaped_arr = arr.reshape(1, 5)
print(reshaped_arr)

[[1 2 3 4 5]]


In [27]:
# Indexing and slicing
print(arr[2])  
print(arr[1:4])

3
[2 3 4]


In [28]:
#NumPy is a fundamental building block for implementing machine learning algorithms and handling data in machine learning tasks.

In [29]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [30]:
# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

In [37]:
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

